// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	twittergraphql "github.com/newsunbanjade/twitter_graphqp"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, username
func (_m *UserRepo) Create(ctx context.Context, username twittergraphql.User) (twittergraphql.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 twittergraphql.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, twittergraphql.User) (twittergraphql.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, twittergraphql.User) twittergraphql.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(twittergraphql.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, twittergraphql.User) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, username
func (_m *UserRepo) GetByEmail(ctx context.Context, username string) (twittergraphql.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 twittergraphql.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (twittergraphql.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) twittergraphql.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(twittergraphql.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepo) GetByUsername(ctx context.Context, username string) (twittergraphql.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 twittergraphql.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (twittergraphql.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) twittergraphql.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(twittergraphql.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
